creation_rules:
  # Development environment
  - path_regex: \.env\.dev\.enc\.yaml$
    age: >-
      age1wfskjehsyd5v49hxjq79mt5y0htjx747aw24jk0ypdkm6tl08fuq9m956q
    encrypted_regex: ^(data|stringData)$
  
  # Production environment
  - path_regex: \.env\.prod\.enc\.yaml$
    age: >-
      age1wfskjehsyd5v49hxjq79mt5y0htjx747aw24jk0ypdkm6tl08fuq9m956q
    encrypted_regex: ^(data|stringData)$
  
  # Kubernetes secrets
  - path_regex: kubernetes-secrets.*\.enc\.yaml$
    age: >-
      age1wfskjehsyd5v49hxjq79mt5y0htjx747aw24jk0ypdkm6tl08fuq9m956q
    encrypted_regex: ^(data|stringData)$

# Default rule for any other encrypted files
  - age: >-
      age1wfskjehsyd5v49hxjq79mt5y0htjx747aw24jk0ypdkm6tl08fuq9m956q
    encrypted_regex: ^(data|stringData)$
