# Kubernetes Secrets (Encrypted with SOPS)
# This file contains sensitive configuration for Kubernetes deployments
# Decrypt using: sops -d kubernetes-secrets.enc.yaml

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: unity-database
  labels:
    app: mongodb
    component: database
type: Opaque
data:
  username: bW9uZ28=  # "mongo" in base64
  password: bW9uZ29wYXNz  # "mongopass" in base64
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: unity-database
  labels:
    app: unity-api
    component: backend
type: Opaque
data:
  jwt_secret: ZGV2LWp3dC1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u  # base64 encoded
  db_password: ZGV2X3Bhc3N3b3JkXzEyMw==  # base64 encoded
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: unity-database
  labels:
    app: unity-api
    component: backend
data:
  NODE_ENV: "development"
  PORT: "3000"
  LOG_LEVEL: "debug"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
