apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unity-database

resources:
  - namespace.yaml
  - mongodb-deployment.yaml

commonLabels:
  app.kubernetes.io/name: unity-api
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: unity-project

images:
  - name: mongo
    newTag: "7.0"

# Add common annotations
commonAnnotations:
  description: "MongoDB deployment for Unity API backend"
  maintainer: "Unity API Team"
